version: '3.7'

services:
  app-recommendation:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: RECOMMENDATION
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app
 